bpe_tokenizer_src:
  bpe: sentencepiece
  sentencepiece_model: ${SENTENCE_PIECE_MODEL}  # Path to the SentencePiece model
input_channels: 1
input_feat_per_channel: 80
sampling_alpha: 1.0
specaugment:
  freq_mask_F: 27
  freq_mask_N: 1
  time_mask_N: 1
  time_mask_T: 100
  time_mask_p: 1.0
  time_wrap_W: 0
transforms:
  '*':
  - utterance_cmvn
  _train:
  - utterance_cmvn
  - specaugment
vocab_filename: ${VOCABULARY}  # Path to the Vocabulary file
vocab_filename_src: ${VOCABULARY}
